name: CD 

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: goldenowl-testapp
      ECR_REGISTRY: 248189929339.dkr.ecr.us-east-1.amazonaws.com
    steps:
      - name: Checkout repository         
        uses: actions/checkout@v4

      - name: Download version.txt artifact and read version
        uses: actions/download-artifact@v3
        with:
          name: version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: goldenowl-testapp-task-defination.json
          container-name: goldenowl-testapp
          image: ${{env.ECR_REGISTRY}}/${{env.IMAGE_NAME}}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition}}
          service: 
          cluster: dev-cluster
          wait-for-service-stability: true  