name: CD 

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository         
        uses: actions/checkout@v4

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: goldenowl-testapp-task-defination.json
          container-name: goldenowl-testapp
          image: ${{ steps.build-image.outputs.image }}    

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition}}
          service: goldenowl-testapp
          cluster: dev-cluster
          wait-for-service-stability: true 