name: CD 

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository         
        uses: actions/checkout@v4