name: CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest      
    steps:       
      - name: Checkout repository         
        uses: actions/checkout@v4

      - name: test case         
        run:            
          echo "Test case is running..."

  build:
    runs-on: ubuntu-latest      
    steps:       
      - name: Checkout repository         
        uses: actions/checkout@v4

      - name: notify build         
        run:            
          echo "Build is running..."
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: docker build -t goldenowl-testapp ./src
      
      - name: Push Docker Image
        run: docker push goldenowl-testapp
