name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest      
    steps:       
      - name: Checkout repository         
        uses: actions/checkout@v4

      - name: Testing
        run: |
          cd src
          npm i
          npm test

  build:
    runs-on: ubuntu-latest      
    env:
      IMAGE_NAME: goldenowl-testapp
      ECR_REGISTRY: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
    steps:       
      - name: Checkout repository         
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Run build script
        env: 
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          AWS-ACCESS-KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS-SECRET-ACCESSKEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS-REGION: ${{ vars.AWS_REGION }}
        run: | 
          chmod +x build.sh
          ./build.sh



  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout repository         
  #       uses: actions/checkout@v4

  #     - name: Run deploy script
  #       run: |
  #         chmod +x deploy.sh
  #         ./deploy.sh
